networks: 
    seven-pet:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes: 
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        depends_on: 
            - app
            - mysql
        networks: 
            - seven-pet
            
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3307:3306"
        volumes: 
            - ./src/.mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: seven-pet
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        networks: 
            - seven-pet

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - seven-pet        
            
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
            - "5173:5173"
        networks: 
            - seven-pet